name: glass_bottom_navigation_example
description: Example app for the glass_bottom_navigation package.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  glass_bottom_navigation:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
